modLoader="javafml"
loaderVersion="[43,)"
license="Academic Free License v3.0"

[[mods]]
modId="tech_odyssey_beyond_the_limits"
version="1.0.0"
displayName="Tech Odyssey: Beyond the Limits"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Momossim"

[[dependencies.tech_odyssey_beyond_the_limits]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"




